---
- name: Ensure loading of local facts
  setup: filter=ansible_local
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: activate

- name: Activate patched ABE
  shell: /usr/sbin/luactivate {{ ansible_local.pca.abe.pending }}
  register: activated
  changed_when: "activated.stdout != 'WARNING: Boot environment <{{ ansible_local.pca.abe.pending }}> is already activated.'"
  notify: reboot sequence
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: activate
